# Generated by Django 4.1.6 on 2023-02-13 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_grupoveiculos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=7)),
                ('grupo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='core.grupoveiculos')),
            ],
        ),
    ]
