# Generated by Django 4.1.6 on 2023-02-13 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_veiculo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GrupoVeiculos',
            new_name='GrupoVeiculo',
        ),
    ]
